---
CONFIG_MAX_CPU_NUM:
  value: 8
  type: usize
  description: |
    Maximum number of supported CPUs.


CONFIG_PAGE_SIZE:
  value: 4096
  type: usize
  description: |
    Page size.

CONFIG_LOG_LEVEL:
  value: crate::kernel::printer::LogLevel::Trace
  type: crate::kernel::printer::LogLevel
  description: |
    Log level filtering used by [`printk`](crate::kernel::printer::Printer)..
...
